version: '3.8'
services:
  mina-daemon:
    entrypoint:
      - /usr/bin/env
      - bash
      - -c
      - |
        /app/scripts/generate-ledger-hf-dryrun.sh -p 2 \
                                                  -k 6 \
                                                  -e 2 \
                                                  -b 7000000 \
                                                  --mina-binary $(which mina) \
                                                  --runtime-genesis-ledger-binary $(which mina-create-genesis) \
                                                  --output-dir /output \
                                                  --prefix ${LEDGER_PREFIX:-new-devnet}
