version: '3.8'
services:
  mina-daemon:
    volumes:
      - ~/github/mina:/app/:rw
    environment:
      - GENESIS_TIMESTAMP=${GENESIS_TIMESTAMP}
    entrypoint:
      - /usr/bin/env
      - bash
      - -c
      - |
        chmod +x /app/scripts/generate-ledger-hf-dryrun.sh
        /app/scripts/generate-ledger-hf-dryrun.sh -p 30 \
                                                  -k 20 \
                                                  -e 0 \
                                                  -b 10000 \
                                                  --plain-balance 10000 \
                                                  --mina-binary $(which mina) \
                                                  --runtime-genesis-ledger-binary $(which mina-create-genesis) \
                                                  --output-dir /output \
                                                  --pad-app-state \
                                                  --timestamp ${GENESIS_TIMESTAMP} \
                                                  --prefix ${LEDGER_PREFIX:-new-devnet}
